var map03 = { "height":30,
    keyMap: [0, res.tile_4, res.tile_3, res.tile_5, res.tile_1, 0, res.tile_7, res.tile_6, res.tile_8],
    // 4 is rock.png, 1 is lwall.png, 6 is upwall.png, 3 is center.png, 2 is rwall.png, 8 is downwall.png, 7 is starttile.png
    "layers":[
    {
        "data":[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 6, 3, 6, 6, 3, 6, 6, 4, 4, 4, 4, 6, 3, 2, 4, 4, 4, 1, 3, 3, 3, 6, 6, 6, 6, 3, 6, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 4, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 1, 3, 3, 3, 2, 4, 4, 4, 1, 3, 3, 3, 3, 3, 2, 4, 4, 1, 3, 3, 2, 4, 4, 4, 4, 4, 6, 6, 4, 4, 1, 3, 3, 3, 3, 2, 4, 4, 4, 4, 1, 3, 3, 2, 4, 4, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 1, 3, 2, 4, 4, 4, 3, 4, 4, 4, 4, 4, 1, 3, 3, 3, 3, 2, 4, 4, 1, 3, 3, 3, 3, 8, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 1, 3, 3, 3, 2, 4, 4, 4, 4, 4, 1, 3, 6, 6, 3, 3, 3, 3, 3, 3, 2, 4, 1, 3, 3, 8, 8, 4, 4, 3, 3, 3, 2, 4, 3, 2, 4, 4, 4, 4, 1, 3, 3, 3, 2, 4, 4, 4, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 1, 3, 3, 4, 4, 4, 4, 3, 3, 2, 4, 4, 3, 2, 4, 4, 4, 4, 4, 1, 3, 3, 2, 4, 4, 1, 3, 3, 3, 3, 3, 3, 4, 4, 4, 1, 3, 3, 2, 4, 4, 8, 4, 4, 4, 4, 3, 3, 3, 2, 4, 3, 2, 4, 4, 4, 4, 4, 4, 4, 3, 3, 2, 4, 4, 1, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 4, 3, 3, 2, 4, 4, 4, 1, 3, 3, 3, 3, 2, 4, 4, 2, 4, 4, 4, 1, 3, 6, 4, 4, 1, 3, 2, 4, 4, 3, 3, 8, 3, 3, 4, 4, 1, 3, 3, 3, 3, 3, 3, 3, 2, 4, 1, 3, 3, 3, 3, 3, 4, 4, 1, 2, 4, 1, 3, 3, 3, 3, 6, 7, 4, 3, 4, 4, 4, 3, 3, 4, 3, 3, 4, 4, 1, 3, 4, 1, 3, 3, 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 2, 4, 4, 2, 4, 1, 4, 3, 4, 4, 4, 4, 4, 3, 4, 4, 4, 1, 3, 4, 8, 3, 6, 4, 1, 3, 3, 3, 3, 4, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 4, 3, 3, 3, 4, 3, 2, 4, 4, 2, 4, 3, 4, 4, 4, 1, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 4, 1, 3, 4, 3, 3, 6, 6, 3, 3, 3, 4, 4, 4, 1, 3, 4, 4, 3, 3, 6, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 1, 3, 3, 3, 3, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, 4, 4, 4, 4, 3, 4, 4, 4, 8, 3, 3, 4, 3, 4, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 1, 3, 3, 4, 4, 4, 1, 4, 6, 6, 6, 3, 2, 4, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 4, 3, 3, 3, 3, 4, 3, 3, 4, 1, 3, 3, 3, 3, 3, 3, 3, 6, 6, 3, 3, 3, 3, 3, 4, 4, 4, 4, 1, 4, 4, 4, 1, 6, 6, 4, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 1, 3, 3, 3, 3, 4, 4, 1, 4, 4, 4, 4, 4, 3, 6, 6, 3, 4, 4, 4, 1, 3, 3, 6, 4, 6, 3, 3, 2, 4, 3, 3, 3, 3, 3, 4, 1, 3, 3, 3, 3, 3, 3, 3, 2, 4, 4, 1, 3, 4, 4, 1, 3, 3, 4, 1, 3, 4, 4, 4, 1, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3, 4, 1, 3, 3, 3, 3, 3, 3, 3, 4, 1, 3, 3, 4, 4, 4, 3, 4, 4, 1, 4, 3, 4, 1, 3, 2, 4, 4, 1, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 1, 3, 3, 3, 3, 2, 4, 4, 4, 3, 4, 4, 1, 4, 3, 4, 4, 3, 4, 4, 4, 1, 3, 4, 4, 4, 4, 4, 4, 4, 3, 4, 1, 3, 3, 4, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 1, 4, 3, 2, 4, 3, 4, 4, 4, 4, 4, 4, 3, 6, 6, 6, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 1, 3, 3, 2, 4, 4, 4, 4, 3, 4, 1, 3, 4, 3, 4, 4, 3, 4, 4, 4, 4, 6, 6, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 1, 3, 4, 4, 3, 4, 3, 4, 6, 3, 6, 4, 4, 1, 3, 3, 3, 3, 3, 3, 3, 2, 4, 2, 4, 3, 3, 4, 1, 3, 3, 3, 3, 3, 3, 2, 4, 4, 2, 4, 4, 1, 3, 3, 3, 4, 8, 6, 8, 4, 2, 4, 4, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 4, 4, 4, 1, 3, 2, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 2, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 2, 4, 4, 4, 4, 4, 1, 4, 1, 4, 3, 2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 4, 4, 1, 3, 8, 8, 8, 3, 8, 4, 4, 8, 8, 3, 3, 8, 8, 4, 4, 1, 6, 6, 3, 8, 4, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        "height":30,
        "name":"Tile Layer 1",
        "opacity":1,
        "type":"tilelayer",
        "visible":true,
        "width":40,
        "x":0,
        "y":0
    },
    {
        "draworder":"topdown",
        "height":30,
        "name":"Object Layer 1",
        "objects":[
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":-150
                    },
                    {
                        "x":50,
                        "y":-150
                    },
                    {
                        "x":50,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":375,
                "y":975
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":-250,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":325,
                "y":525
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":100
                    },
                    {
                        "x":-300,
                        "y":100
                    },
                    {
                        "x":-300,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":675,
                "y":325
            },
            {
                "height":200,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":150,
                "x":575,
                "y":575
            },
            {
                "height":150,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":150,
                "x":525,
                "y":725
            },
            {
                "height":250,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":150,
                "x":775,
                "y":675
            },
            {
                "height":150,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":250,
                "x":1025,
                "y":725
            },
            {
                "height":100,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":200,
                "x":525,
                "y":1075
            },
            {
                "height":150,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":150,
                "x":625,
                "y":925
            },
            {
                "height":250,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":250,
                "x":675,
                "y":1175
            },
            {
                "height":250,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":250,
                "x":825,
                "y":1025
            },
            {
                "height":200,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":100,
                "x":975,
                "y":825
            },
            {
                "height":150,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":150,
                "x":875,
                "y":975
            },
            {
                "height":200,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":100,
                "x":1175,
                "y":925
            },
            {
                "height":150,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":200,
                "x":975,
                "y":525
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":-100
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":525,
                "y":1425
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":200
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":425,
                "y":1225
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":150
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":475,
                "y":1275
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":237.5
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":325,
                "y":1175
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":400,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":125,
                "y":1375
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":250,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":175,
                "y":1275
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":300,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":75,
                "y":1325
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":225,
                "y":1175
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":175,
                "y":1225
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1025,
                "y":1025
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":-350
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":125,
                "y":775
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":125,
                "y":825
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":225,
                "y":375
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1325,
                "y":575
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":625,
                "y":725
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":825,
                "y":1175
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1175,
                "y":1275
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":475,
                "y":975
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":150,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1275,
                "y":1325
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":550,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1375,
                "y":1425
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":350
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1625,
                "y":975
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":-400
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1475,
                "y":1225
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":-300
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1875,
                "y":1225
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":-250
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1725,
                "y":1175
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":200,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1575,
                "y":825
            },
            {
                "height":150,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":100,
                "x":1475,
                "y":575
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":-250,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1875,
                "y":725
            },
            {
                "height":150,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":50,
                "x":1625,
                "y":425
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":-750,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":825,
                "y":175
            },
            {
                "height":200,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":100,
                "x":125,
                "y":75
            },
            {
                "height":100,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":300,
                "x":175,
                "y":125
            },
            {
                "height":100,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":150,
                "x":275,
                "y":75
            },
            {
                "height":200,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":600,
                "x":1075,
                "y":125
            },
            {
                "height":300,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":400,
                "x":875,
                "y":175
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":200
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":475,
                "y":525
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":200
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":575,
                "y":1175
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":125,
                "y":325
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":125,
                "y":75
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":875,
                "y":475
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1625,
                "y":175
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1075,
                "y":1425
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1925,
                "y":1025
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1475,
                "y":825
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1725,
                "y":325
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1725,
                "y":375
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1125,
                "y":275
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":725,
                "y":75
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":1775,
                "y":1125
            }],
        "opacity":1,
        "type":"objectgroup",
        "visible":true,
        "width":40,
        "x":0,
        "y":0
    }],
    "orientation":"orthogonal",
    "properties":
    {

    },
    "renderorder":"right-down",
    "tileheight":100,
    "tilesets":[
    {
        "firstgid":1,
        "image":"Sprites\/Tiles\/Tile02.png",
        "imageheight":100,
        "imagewidth":100,
        "margin":0,
        "name":"Tile02",
        "properties":
        {

        },
        "spacing":0,
        "tileheight":50,
        "tilewidth":50
    }],
    "tilewidth":100,
    "version":1,
    "width":40
};