var map02 = { "height":15,
    "layers":[
    {
        "draworder":"topdown",
        "height":15,
        "name":"Object Layer 1",
        "objects":[
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":675,
                "y":225
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":325,
                "y":225
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":225,
                "y":625
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":525,
                "y":375
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":875,
                "y":75
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":775,
                "y":525
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":475,
                "y":425
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":125,
                "y":225
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":-350
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":75,
                "y":525
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":50
                    },
                    {
                        "x":50,
                        "y":50
                    },
                    {
                        "x":50,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":875,
                "y":625
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":-200,
                        "y":0
                    },
                    {
                        "x":-200,
                        "y":50
                    },
                    {
                        "x":0,
                        "y":50
                    },
                    {
                        "x":0,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":425,
                "y":625
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":200,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":725,
                "y":225
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":775,
                "y":75
            },
            {
                "ellipse":true,
                "height":0,
                "name":"",
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":775,
                "y":125
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":200
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":725,
                "y":325
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":200
                    },
                    {
                        "x":150,
                        "y":200
                    },
                    {
                        "x":150,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":425,
                "y":275
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":400
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":525,
                "y":175
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":50,
                        "y":0
                    },
                    {
                        "x":50,
                        "y":300
                    },
                    {
                        "x":0,
                        "y":300
                    },
                    {
                        "x":0,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":225,
                "y":225
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":50
                    },
                    {
                        "x":-350,
                        "y":50
                    },
                    {
                        "x":-350,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":725,
                "y":75
            },
            {
                "height":0,
                "name":"",
                "polyline":[
                    {
                        "x":0,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":50
                    },
                    {
                        "x":-300,
                        "y":50
                    },
                    {
                        "x":-300,
                        "y":0
                    },
                    {
                        "x":0,
                        "y":0
                    }],
                "properties":
                {

                },
                "rotation":0,
                "type":"",
                "visible":true,
                "width":0,
                "x":575,
                "y":75
            }],
        "opacity":1,
        "type":"objectgroup",
        "visible":true,
        "width":20,
        "x":0,
        "y":0
    },
    {
        "data":[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 4, 4, 4, 4, 4, 4, 4, 5, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 8, 5, 6, 4, 4, 5, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 8, 5, 6, 4, 4, 5, 7, 8, 8, 8, 8, 8, 8, 5, 7, 8, 8, 8, 8, 8, 8, 5, 6, 4, 4, 5, 7, 8, 5, 7, 6, 8, 8, 7, 7, 8, 8, 5, 7, 7, 7, 7, 6, 4, 4, 5, 7, 8, 5, 6, 8, 8, 5, 7, 7, 6, 8, 8, 8, 8, 8, 7, 6, 4, 4, 5, 7, 8, 5, 6, 8, 5, 7, 7, 7, 7, 6, 8, 5, 6, 8, 7, 6, 4, 4, 5, 7, 7, 7, 6, 8, 5, 7, 7, 7, 7, 7, 7, 7, 7, 8, 7, 6, 4, 8, 5, 7, 8, 5, 6, 8, 5, 7, 7, 7, 7, 6, 8, 5, 7, 8, 7, 6, 4, 4, 5, 7, 8, 5, 6, 8, 8, 5, 7, 7, 6, 8, 8, 7, 7, 8, 7, 6, 4, 4, 5, 7, 8, 5, 7, 6, 8, 8, 5, 6, 8, 8, 5, 7, 6, 8, 7, 6, 4, 4, 5, 7, 8, 8, 8, 5, 8, 8, 7, 6, 8, 8, 5, 8, 8, 8, 7, 6, 4, 4, 5, 7, 8, 5, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 4, 4, 5, 7, 8, 5, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 8, 8, 8, 8, 8, 8, 8],
        "height":15,
        "name":"Tile Layer 1",
        "opacity":1,
        "type":"tilelayer",
        "visible":true,
        "width":20,
        "x":0,
        "y":0
    }],
    keyMap: [0, 0, 0, 0, res.tile_1, res.tile_2, res.tile_4, res.tile_3],
    "orientation":"orthogonal",
    "properties":
    {

    },
    "renderorder":"right-down",
    "tileheight":100,
    "tilesets":[
    {
        "firstgid":1,
        "image":"Sprites\/Tiles\/Tile01.png",
        "imageheight":100,
        "imagewidth":100,
        "margin":0,
        "name":"Tile01",
        "properties":
        {

        },
        "spacing":0,
        "tileheight":100,
        "tilewidth":50
    },
    {
        "firstgid":5,
        "image":"Sprites\/Tiles\/Tile02.png",
        "imageheight":100,
        "imagewidth":100,
        "margin":0,
        "name":"Tile02",
        "properties":
        {

        },
        "spacing":0,
        "tileheight":50,
        "tilewidth":50
    }],
    "tilewidth":100,
    "version":1,
    "width":20
};